### ISSUE TITLE
Implementing Feed Page UI

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#259] opened 2023-10-24 16:50 UTC
### Problem Definition

We decided to work on feed page ui this week and started the implementation of necessary components. After poll card an sidebar is finished, the feed page will be created.

### Acceptance Criteria

The Feed page UI shall be submitted and reviewed by the members of the front-end team.

**Comment by selinisik** [comment] 2023-10-29 23:38
I have finalized the feed page design. Here is my pr [#280](https://github.com/bounswe/bounswe2023group4/pull/280).

**Comment by EmreBatuhan** [comment] 2023-10-30 20:45
The page looks good. The pr is merged so the issue is over.

**Closed by EmreBatuhan** 2023-10-30 20:45 UTC
Labels: Priority: Medium, Status: In Review, Type: Feature, Platform: Frontend
